### ISSUE TITLE
沒反應

### ISSUE THREAD

**Issue by Rainbowrain-TW** [OpenLive3D/OpenLive3D.github.io#8]
Chrome v102.0.5005.63

我不確定是不是要連動 cam 之後才能正常測試？
總之我網頁打開，點那幾個表情按鈕都沒反應
setting 調了背景，這個有 work，按 enter 或觸發 onblur 就會反應變化
body 跟 mouth 按照 info 提示的範圍試了幾個數值都沒變化

如果想要有人用的話，弄一下使用說明吧
都英文還要自己摸索，還要來 github report，這種使用者太稀有了吧

**Comment by Wei-1** [comment]
Thanks for the testing!
Only if the Cam is connected will the 3D model be updated.
Do you have the camera permission set for the browser?

**Comment by Wei-1** [comment]
Permission handled with version alpha-0.3.3
By adding a loading screen with pre-requirements check
https://github.com/OpenLive3D/OpenLive3D.github.io/commit/77493281851b8910ad9b4c42266fc746c0fa1b98
